name: Build project

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2

      - name: Setup JDK
        uses: actions/setup-java@v3.4.1
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build and test
        run: |
          chmod +x gradlew
          ./gradlew clean build

      - name: Analyse
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonarqube

      - name: Publish to Maven Central
        if: ${{ github.ref == 'refs/heads/develop' }}
        env:
          SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
        run:
          ./gradlew publish
