name: Build project

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3

      - name: Set up JDK 8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '8'

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew clean build

      - name: Run tests
        run:
          ./gradlew test

      - name: Publish to Maven Central
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
        run:
          ./gradlew publish